---
- hosts: all
  vars:
    #
    # REQUIRED
    #
    # ddns_zones: string[]
    # ddns_record_names: string[]
    # ddns_access_key: string
    # ddns_access_secret: string
    #
    # OPTIONAL
    #
    # ddns_config_dir: /srv/route53-ddns
    # ddns_container_registry_username: string
    # ddns_container_registry_password: string
    # ddns_container_registry: ghcr.io
    # ddns_container_name: hobointhecorner/hobo.route53-ddns
    # ddns_container_tag: stable
    # ddns_container_force_pull: false
    # ddns_additional_parameters: []
    # ddns_ttl_sec: 21600

  handlers:
    - name: Reload route53-ddns service
      become: yes
      when: not ansible_check_mode
      systemd:
        name: route53-ddns
        enabled: yes
        daemon_reload: yes
        state: restarted

  tasks:
    - name: Set facts
      set_fact:
        ddns_container: "{{ ddns_container_registry|default('ghcr.io') }}/{{ ddns_container_name|default('hobointhecorner/hobo.route53-ddns') }}:{{ ddns_container_tag|default('stable', true) }}"
        ddns_login_required: >-
          {% if ddns_container_registry_username is defined and ddns_container_registry_password is defined -%}
          {{ true }}
          {%- else -%}
          {{ false }}
          {%- endif %}

    - name: Ensure config directory
      become: yes
      file:
        path: "{{ ddns_config_dir|default('/srv/route53-ddns') }}"
        state: directory
        owner: root
        group: root
        mode: "2660"

    - name: Template config files
      become: yes
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "templates/.env.j2",                 dest: "{{ ddns_config_dir|default('/srv/route53-ddns') }}/.env" }
        - { src: "templates/route53-ddns.service.j2", dest: "/etc/systemd/system/route53-ddns.service"}
      notify:
        - Reload route53-ddns service

    - when: ddns_login_required
      block:
        - name: Ensure registry token file
          become: yes
          copy:
            dest: "{{ ddns_config_dir|default('/srv/route53-ddns') }}/.registry_token"
            content: "{{ ddns_container_registry_password }}"
            owner: root
            group: root
            mode: "660"

        - name: Ensure registry login script
          become: yes
          template:
            src: templates/docker_login.sh.j2
            dest: "{{ ddns_config_dir|default('/srv/route53-ddns') }}/docker_login.sh"
            owner: root
            group: root
            mode: "775"

        - name: Docker login
          docker_login:
            registry: "{{ ddns_container_registry|default('ghcr.io') }}"
            username: "{{ ddns_container_registry_username }}"
            password: "{{ ddns_container_registry_password }}"

    - name: Pull container image
      docker_image:
        name: "{{ ddns_container }}"
        source: pull
        force_source: "{{ ddns_container_force_pull|default(false) }}"
      notify:
        - Reload route53-ddns service
